[package]
name = "pax"
version = "0.4.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
proc-macro2 = { version = "1", default-features = false, features = ["span-locations"] }
syn = { version = "2", default-features = false, features = ["full", "parsing", "clone-impls"] }
